sudo: true

jobs:
  include:
    - stage: Tests
      name: Unit Tests
      if: type = pull_request OR type = push AND branch =~ /^master|[0-9]+-(dev|stable)$/ OR type = cron
      language: node_js
      node_js: 8

      before_install:
        - sudo sysctl -w vm.max_map_count=262144
        - sudo sysctl -w fs.inotify.max_user_watches=524288

      script:
        # Run tests
        - npm install --unsafe-perm && npm test

    - stage: Tests
      name: Dead link check
      if: type = pull_request OR type = push AND branch =~ /^master|[0-9]+-(dev|stable)$/ OR type = cron

      before_script:
        - npm run doc-prepare
        - npm run --prefix doc/framework clone-repos
      script:
        - gem install typhoeus
        - HYDRA_MAX_CONCURRENCY=20 npm run --prefix doc/framework dead-links

    - stage: Deployment Doc Dev
      name: Deploy next-docs.kuzzle.io
      if: branch = 1-dev
      language: node_js
      node_js: 10
      env:
        - NODE_ENV=production
        - S3_BUCKET=docs-next.kuzzle.io
        - CLOUDFRONT_DISTRIBUTION_ID=E2ZCCEK9GRB49U
        - AWS_DEFAULT_REGION=us-west-2
        - AWS_ACCESS_KEY_ID=AKIAIYAXFUAHXOWP2MJA
        # AWS_SECRET_ACCESS_KEY
        - secure: "SQJfdelxmKE2ogwmgyh3lzedBxf/Qg17mlSWKGmdYaXAfjWDS5+wjzz92Mo29GVF4iucKrEFfTTA8/eTuXeJHvx2J/GeUY4TiINAeWT/CVrzSqzaIX0/Xu72438/fE3BrhwbFokKIwKBQjYJjHuqhKFCxpBqto5R+a3zj2WZtR9LT3kaN4Usm3izOBoZqgnlRsIzV1ZHX2q6jhYbqvi9dLburwEsbwq9txTyt/+HkJI870Ojomom9duYEMGWs7xANyzLHCLdqEXlk1FWurhJlCF7B9kI4e7EDHysujI4+28o4TL/5aq1WQ6yRIYE7MYdFzVRboWI5ZMWw6vIKGDwRxOKLnJ679cF4T3Us+F/DUg7spGSs/bg/Sqh2oVK0T8sNvK/jIv9CtUUKql5Nu1e6JHVc3S+vo2jDDjj6eKFiVyKhFy/yZaTmYSZJM4CqeHYevPOQrYTqiMS3T56e1p5RDROqo6cA+ZpdDY1ubheuj9xS8NiXcpcLQLsK/9qZQbZyKBhV24g0JbzYXUXyt0jAXjEzioHy+dCocjbDeL1KW4651zPQVltPNqF1VqTkthbScRPCkwVr5knF5qhdLfH50BMJueyW6hqAUh47LjBM0Z++RdZ8ITykUm5kS/hDclkHOb3sTv5SQ+g3y/cAlmojb0j+m7G81glJfbUB7n7Po4="

      addons:
        apt:
          packages:
            - python
            - python-pip

      install:
        - pip install awscli --upgrade --user

      script:
        - npm run doc-prepare
        - npm run doc-build

      deploy:
        provider: script
        script:
          - npm run doc-upload
        skip_cleanup: true
        on:
          branch: 1-dev

      after_deploy:
        - npm run doc-cloudfront

    # - stage: Deployment Doc Prod
    #   name: Deploy docs.kuzzle.io
    #   if: branch = master
    #   language: node_js
    #   node_js: 10
    #   env:
    #     - NODE_ENV=production
    #     - S3_BUCKET=docs.kuzzle.io
    #     - CLOUDFRONT_DISTRIBUTION_ID=E3D6RP0POLCJMM
    #     - AWS_DEFAULT_REGION=us-west-2
    #     # AWS_ACCESS_KEY_ID
    #     - secure: "0VUGNqpM0z8WGMaD3ZqgV878x8Zxfh753Ox4s4cgBldk1lcTD1DzoCJuk6uzIeOIZkYEyq5APmW5V0hqB3l3lswAoVi/QieJ8VPh6axmcrDo4s2aekDhLR00zIlS6hcVoCjeOcbgxw/vWXEeNbTW5gF6XJcbhHRjT6MbudIGvxxBg84Yyt7lMUmqBOWtNyWpQPuuUKnUDubvoMlmjbbaSfllH6f83zNaGDyygUiRkuSeQRK5GKK1/lcloQBantSm+JPwCUm9TKQyU6AXH4vdvKRdiCO1lhYBa9Eealab71lLPqRJt8tKZqCeYx7ou4FByZpGQ78/rvq0Mr/nfFZA7ECrBJIDd3QYl2mFhwaHVs8VyikIKR/ZaaZ38iw1ISEIVmMH5aTlACv8725T5o2Ej1jcYXdOityf9M0u/FhmqYLnOB6RyES+YMfKBcQ3ULC+pHzJYM5ExzvIw45P82XVEq97whLHGA41nAgcKUsdzMy95a2BI/tIGK4S9BN/P8sbx0kvTeBgLwBqy7CgUKX674strMwHQ8sLylztU4jM62dMo0+Rhw3dLMQ8fkSjCyKRP78BX0ic9uB0Kk5ZhcnjdH/f9L4bjjwvUUZvEbeFtDSDVdxgmurjqxrpDiqfETQ7f4KUia8tzApRuHkdJGFOIcNf22DxursmN8dMJzIGNRw="
    #     # AWS_SECRET_ACCESS_KEY
    #     - secure: "HU48VGBdv/GyVAm6g8eiA3DbKoAPL98AeORbF7UhKLQenxmQRGb1gfdMPNLdop35+95SlxcFC9ogoHcqLBSPLLcTSX57faWpNacD/7j69Z03avgdmfaFOGMOwGd5tOdq4pYmis34xyGJW1kpwAl2U6jp/pcBXABDnCLfRS5kJUsXvrwdE75UACoXQ1tXEtqq9y5LcFo/dGYrhuVvqYQmAUA+ExrfXaIKtUSf2tN5CvYL0cSxLyoQlnbbIQvouyNRyfuGFqNHc3jyBOc/nZWHS0ES91+6ddwZs/i9Fs98TfB3JS9x+gKYWrhDmxek/fOy22+qYUHQ81txk4SQ3GILWiWTfWOTdsBU+Y0FYnC5syLAqpdIstBhmMUUS8NWs5HdYmBv4q0zkTiwBGL/wrLwXkAcLLKUNOrUeMAL1fjQuVRC3hzql15s/A2LwPOR6xwyCu1mH8GKogYulGVWOEHQuk8bC3MaKgDr/4ZoUlCC9Q+mYP/WT+t/NA/0OQIvZVhVVilXk1MTbQMkvrBSuiuxACsyFGVNrkLaC8x2Pjyd2kgZaIv4c2JiiWfvW5IZd7xeyLLKESOfHP8rIf60jmvE7hxD9Yje7JXjo0uvnpEGx2PuMSq5zeUynoLaa8AIMAJ9an3fgdfKKcZ/XPOCAgpmxnKH+leAQx86qwxdAAIkgPY="

    #   addons:
    #     apt:
    #       packages:
    #         - python
    #         - python-pip

    #   install:
    #     - pip install awscli --upgrade --user

    #   script:
    #     - npm run doc-prepare
    #     - npm run doc-build

    #   deploy:
    #     provider: script
    #     script:
    #       - npm run doc-upload
    #     skip_cleanup: true
    #     on:
    #       branch: master

    #   after_deploy:
    #     - npm run doc-cloudfront
