sudo: true

env:
  global:
    - AWS_ACCESS_KEY_ID=AKIAIYAXFUAHXOWP2MJA
    # AWS_SECRET_ACCESS_KEY
    - secure: "t0RVV7ZWMWcoanzVzv1e7v076dWYPn4SeDKVHd6EVV8l07nNuyAEeV3ifgk52/pdgyU5VauJqK++crivOp9uIGHC1QBy0nr/1MK5iOiZRLdKIlf1GW/RcNGducMqqeYatovqMAkzvrz73l5pgd2nF/lK+6KNni3jV6BZfzU5ZE2jZ/MB8ECfPjrveOA1PfipinmS0ma25WCZvv5N+lhlIBWqJescZ1pX/m03qRU2weHLf10gBxufCY586eveT0uS6SAApRltCgrceu9Ol+uQVbdvkc4pUWUFB9Mp/xZO4Mns/iCJQ1nalJut6ULlIm1Kw2+USLlFbwFEmaDFCbizvVt5IwldxnL3j7Sz9rTaEATm+qhg0tDUC00TwOtG6puQ4E9mhXk4yj3WD725aacFqY2JJG41uXMbXp80BvbLzt5sqd+9ARA9wjOYRkRRzGImyXJ7N2tFFX5iUxk002Wota6irYV6WNUwSFt2QJJMNntCKG6HqKuFS5wOgArPvoMpqoRjVoFy1FlB36IAQojSRG2SWn90RkrssyAJ+Ky1Gb3UW7fS9bJbSiXR7aVnyVE9+MvSUyF0JxuGNGkALl7FRGLv60q39Jzq+ubQhOEHMfhbd0H0cgKfe8eV1NnBVEqfvvJicAWhNLoanE8VJ1lnh3d2gRnY+GxnFH4OCigKBH8="

jobs:
  include:
    - stage: Tests
      name: Unit Tests
      if: type = pull_request OR type = push AND branch =~ /^master|[0-9]+-(dev|stable)$/ OR type = cron
      language: node_js
      node_js: 10

      before_install:
        - sudo sysctl -w vm.max_map_count=262144
        - sudo sysctl -w fs.inotify.max_user_watches=524288

      script:
        # Run tests
        - npm install --unsafe-perm && npm test

    - stage: Tests
      name: Dead link check
      if: type = pull_request OR type = push AND branch =~ /^master|[0-9]+-(dev|stable)$/ OR type = cron

      before_script:
        - npm run doc-prepare
        - npm run --prefix doc/framework clone-repos
      script:
        - gem install typhoeus
        - HYDRA_MAX_CONCURRENCY=20 npm run --prefix doc/framework dead-links


    - stage: Deployment Doc Dev
      name: Deploy next-docs.kuzzle.io
      if: type = push AND branch =~ .*-dev
      language: node_js
      node_js: 10
      env:
        - NODE_ENV=production
        - S3_BUCKET=docs-next.kuzzle.io
        - CLOUDFRONT_DISTRIBUTION_ID=E2ZCCEK9GRB49U
        - AWS_DEFAULT_REGION=us-west-2

      addons:
        apt:
          packages:
            - python
            - python-pip

      install:
        - pip install awscli --upgrade --user

      script:
        - npm run doc-prepare
        - npm run doc-build

      deploy:
        provider: script
        script:
          - npm run doc-upload
        skip_cleanup: true

      after_deploy:
        - npm run doc-cloudfront

    - stage: Deployment Doc Prod
      name: Deploy docs.kuzzle.io
      if: type = push AND branch =~ /^master|[0-9]+-stable$/
      language: node_js
      node_js: 10
      env:
        - NODE_ENV=production
        - S3_BUCKET=docs.kuzzle.io
        - CLOUDFRONT_DISTRIBUTION_ID=E3D6RP0POLCJMM
        - AWS_DEFAULT_REGION=us-west-2

      addons:
        apt:
          packages:
            - python
            - python-pip

      install:
        - pip install awscli --upgrade --user

      script:
        - npm run doc-prepare
        - npm run doc-build

      deploy:
        provider: script
        script:
          - npm run doc-upload
        skip_cleanup: true

      after_deploy:
        - npm run doc-cloudfront